image:
  repository: "cr.yandex/crpl7ipeu79oseqhcgn2/ydb-disk-manager"
  pullPolicy: "IfNotPresent"

updateStrategy: "RollingUpdate"
maxUnavailable: "10%"

imagePullSecrets: []
args: []
env:
  - name: DP_DISABLE_PRE_START_CONTAINER
    value: "true"

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  privileged: true

priorityClassName: "system-node-critical"

dnsPolicy: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

diskRegexp: ^sd[a-z][0-9]*$
hostProcPath: /host/proc
updateInterval: 30s
