apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ydb-disk-manager.fullname" . }}-config
data:
  conf.yaml: |
    diskMatch: {{ .Values.diskRegexp | quote }}
    hostProcPath: {{ .Values.hostProcPath | quote }}
    updateInterval: {{ .Values.updateInterval | quote }}
